<?php

/**
 * Sample API
 * PHP version 7.2
 *
 * @package OpenAPIServer
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * This is a sample API
 * The version of the OpenAPI document: 1.0.0
 * Contact: rumatakira74@gmail.com.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace OpenAPIServer\Model;

use OpenAPIServer\BaseModel;

/**
 * CreateDivision
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class CreateDivision extends BaseModel
{
    /**
     * @var string Models namespace.
     * Can be required for data deserialization when model contains referenced schemas.
     */
    protected const MODELS_NAMESPACE = '\OpenAPIServer\Model';

    /**
     * @var string Constant with OAS schema of current class.
     * Should be overwritten by inherited class.
     */
    protected const MODEL_SCHEMA = <<<'SCHEMA'
{
  "required" : [ "divisionAddress", "divisionCity", "divisionCompanyName", "divisionCoordinates", "divisionName", "divisionTimeZonne", "divisionType" ],
  "type" : "object",
  "properties" : {
    "divisionName" : {
      "type" : "string",
      "example" : "Rich Ranch"
    },
    "divisionCity" : {
      "type" : "string",
      "example" : "Tampa"
    },
    "divisionTimeZone" : {
      "type" : "string",
      "example" : "UTC"
    },
    "divisionAddress" : {
      "type" : "string",
      "example" : "777 Beach Crossroad"
    },
    "divisionCoordinates" : {
      "type" : "string",
      "example" : "Latitude 44.666944 Longitude 107.777058"
    },
    "divisionType" : {
      "type" : "string",
      "description" : "enum ('cafe', 'office')",
      "example" : "cafe",
      "enum" : [ "cafe", "office" ]
    },
    "divisionCompanyName" : {
      "type" : "string",
      "example" : "Schimmel-Balistreri"
    }
  }
}
SCHEMA;
}
