<?php

/**
 * Sample API
 * PHP version 7.2
 *
 * @package OpenAPIServer
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * This is a sample API
 * The version of the OpenAPI document: 1.0.0
 * Contact: rumatakira74@gmail.com.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */
namespace OpenAPIServer\Model;

use PHPUnit\Framework\TestCase;
use OpenAPIServer\Model\CreateUser;

/**
 * CreateUserTest Class Doc Comment
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \OpenAPIServer\Model\CreateUser
 */
class CreateUserTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CreateUser"
     */
    public function testCreateUser()
    {
        $testCreateUser = new CreateUser();
        $namespacedClassname = CreateUser::getModelsNamespace() . '\\CreateUser';
        $this->assertSame('\\' . CreateUser::class, $namespacedClassname);
        $this->assertTrue(
            class_exists($namespacedClassname),
            sprintf('Assertion failed that "%s" class exists', $namespacedClassname)
        );
        $this->markTestIncomplete(
            'Test of "CreateUser" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "userRealName"
     */
    public function testPropertyUserRealName()
    {
        $this->markTestIncomplete(
            'Test of "userRealName" property in "CreateUser" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "userLoginName"
     */
    public function testPropertyUserLoginName()
    {
        $this->markTestIncomplete(
            'Test of "userLoginName" property in "CreateUser" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "userPassword"
     */
    public function testPropertyUserPassword()
    {
        $this->markTestIncomplete(
            'Test of "userPassword" property in "CreateUser" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "userPhone"
     */
    public function testPropertyUserPhone()
    {
        $this->markTestIncomplete(
            'Test of "userPhone" property in "CreateUser" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "companyUserBelogsTo"
     */
    public function testPropertyCompanyUserBelogsTo()
    {
        $this->markTestIncomplete(
            'Test of "companyUserBelogsTo" property in "CreateUser" model has not been implemented yet.'
        );
    }

    /**
     * Test getOpenApiSchema static method
     * @covers ::getOpenApiSchema
     */
    public function testGetOpenApiSchema()
    {
        $schemaArr = CreateUser::getOpenApiSchema();
        $this->assertIsArray($schemaArr);
    }
}
