<?php

/**
 * Sample API
 * PHP version 7.2
 *
 * @package OpenAPIServer
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * This is a sample API
 * The version of the OpenAPI document: 1.0.0
 * Contact: rumatakira74@gmail.com.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the endpoint.
 */
namespace OpenAPIServer\Api;

use PHPUnit\Framework\TestCase;
use OpenAPIServer\Api\DivisionsApi;

/**
 * DivisionsApiTest Class Doc Comment
 *
 * @package OpenAPIServer\Api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \OpenAPIServer\Api\DivisionsApi
 */
class DivisionsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createDivision
     *
     * Create division.
     *
     * @covers ::createDivision
     */
    public function testCreateDivision()
    {
        $this->markTestIncomplete(
            'Test of "createDivision" method has not been implemented yet.'
        );
    }

    /**
     * Test case for deleteDivision
     *
     * Delete division.
     *
     * @covers ::deleteDivision
     */
    public function testDeleteDivision()
    {
        $this->markTestIncomplete(
            'Test of "deleteDivision" method has not been implemented yet.'
        );
    }

    /**
     * Test case for getCityDivisions
     *
     * Get divisions in the specified city.
     *
     * @covers ::getCityDivisions
     */
    public function testGetCityDivisions()
    {
        $this->markTestIncomplete(
            'Test of "getCityDivisions" method has not been implemented yet.'
        );
    }

    /**
     * Test case for getDivision
     *
     * Get division.
     *
     * @covers ::getDivision
     */
    public function testGetDivision()
    {
        $this->markTestIncomplete(
            'Test of "getDivision" method has not been implemented yet.'
        );
    }

    /**
     * Test case for getDivisionsAndCities
     *
     * Get cities and divisions in them.
     *
     * @covers ::getDivisionsAndCities
     */
    public function testGetDivisionsAndCities()
    {
        $this->markTestIncomplete(
            'Test of "getDivisionsAndCities" method has not been implemented yet.'
        );
    }

    /**
     * Test case for updateDivision
     *
     * Update division.
     *
     * @covers ::updateDivision
     */
    public function testUpdateDivision()
    {
        $this->markTestIncomplete(
            'Test of "updateDivision" method has not been implemented yet.'
        );
    }
}
