<?php

/**
 * Sample API
 * PHP version 7.2
 *
 * @package OpenAPIServer
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * This is a sample API
 * The version of the OpenAPI document: 1.0.0
 * Contact: rumatakira74@gmail.com.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the endpoint.
 */
namespace OpenAPIServer\Api;

use PHPUnit\Framework\TestCase;
use OpenAPIServer\Api\UserApi;

/**
 * UserApiTest Class Doc Comment
 *
 * @package OpenAPIServer\Api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \OpenAPIServer\Api\UserApi
 */
class UserApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createUser
     *
     * Create user.
     *
     * @covers ::createUser
     */
    public function testCreateUser()
    {
        $this->markTestIncomplete(
            'Test of "createUser" method has not been implemented yet.'
        );
    }

    /**
     * Test case for deleteUser
     *
     * Delete user.
     *
     * @covers ::deleteUser
     */
    public function testDeleteUser()
    {
        $this->markTestIncomplete(
            'Test of "deleteUser" method has not been implemented yet.'
        );
    }

    /**
     * Test case for getUser
     *
     * Get user.
     *
     * @covers ::getUser
     */
    public function testGetUser()
    {
        $this->markTestIncomplete(
            'Test of "getUser" method has not been implemented yet.'
        );
    }

    /**
     * Test case for getUsers
     *
     * Get users which belongs to the same company.
     *
     * @covers ::getUsers
     */
    public function testGetUsers()
    {
        $this->markTestIncomplete(
            'Test of "getUsers" method has not been implemented yet.'
        );
    }

    /**
     * Test case for updateUser
     *
     * Update user.
     *
     * @covers ::updateUser
     */
    public function testUpdateUser()
    {
        $this->markTestIncomplete(
            'Test of "updateUser" method has not been implemented yet.'
        );
    }
}
